package okk.pskProject_JavaEE.mybatis.dao;

import java.util.List;

import okk.pskProject_JavaEE.mybatis.model.Album;
import okk.pskProject_JavaEE.mybatis.model.AlbumRecord;
import okk.pskProject_JavaEE.mybatis.model.Recordlabel;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AlbumRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_RECORD
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    int insert(AlbumRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM_RECORD
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    List<AlbumRecord> selectAll();

    List<Recordlabel> getLabels(Integer id);
}