package okk.pskProject_JavaEE.mybatis.dao;

import okk.pskProject_JavaEE.mybatis.model.Recordlabel;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface RecordlabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECORDLABEL
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECORDLABEL
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    int insert(Recordlabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECORDLABEL
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    Recordlabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECORDLABEL
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    List<Recordlabel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECORDLABEL
     *
     * @mbg.generated Mon Apr 12 19:11:54 EEST 2021
     */
    int updateByPrimaryKey(Recordlabel record);
}